# Page settings
BaseURL = "https://opencybersecurityalliance.org/"
relativeURLs = true
title = "OCA"
languageCode = "en-us"
theme = "hugo-elate-theme"
googleAnalytics = "G-BDQL844N94"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4

[params]

  custom_css = ["/css/custom1.css", "/css/custom2.css", "/css/codeblock.css"]
  baseurl = "https://opencybersecurityalliance.org/"

  # Meta
  author = ""
  description = ""
  email = ""
  mailing_list_subscribe = "https://lists.oasis-open-projects.org/g/oca"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "/img/open-projects-logo.png"
    home = "Home"
    services = "Benefits"
    projects = "Projects"
    testimonials = "Testimonials"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/posts/"
      name = "News"
      weight = 10

  # Hero section
  [params.hero]
    title = "We’re Making Standards-Based, Interoperable Cybersecurity a Reality."
    subtitle = "OCA is building an open ecosystem where cybersecurity products interoperate without the need for customized integrations. Using community-developed standards and practices, we're simplifying integration across the threat lifecycle. Join our community."

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Learn"
    description = "Find out what OCA is doing to increase your security efficiency and effectiveness."
    url = "/posts"
    button = "See New Posts"
    icon = "icon-fire"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Discuss"
    description = "Share your questions, concerns, and ideas for cybersecurity interoperability."
    url = "https://docs.google.com/forms/d/1vEAqg9SKBF3UMtmbJJ9qqLarrXN5zeVG3_obedA3DKs/viewform?edit_requested=true"
    button = "Join Us On Slack"
    icon = "icon-bubbles"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Contribute"
    description = "Be part of the open, diverse community that is the OCA. Everyone is welcome."
    url = "/get-involved"
    button = "Get Involved"
    icon = "icon-energy"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=qZgeJ01cqeQ"
    footertext = '[Watch more OCA Videos](https://www.youtube.com/channel/UCjTpPl2oEGH_Ws251m827Cg)'

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Services section
  [params.services]
    enable = true
    title = "Benefits"
    description = 'Unlike industry-specific platforms for sharing threat data, OCA is uniquely focused on product interoperability, with benefits for the entire cybersecurity community:'

    [[params.services.item]]
      title = "Security Vendors can:"
      description = ""
      benefit1 = "Increase integration exposure and reduce engineering"
      benefit2 = "Leverage open source connectors and add value to your products"
      benefit3 = "Deliver more robust data integrations"
      benefit4 = "Allow clients to extract more value from your tools"
      icon = "icon-cursor"

    [[params.services.item]]
      title = "Security Practitioners can:"
      description = ""
      benefit1 = "Share information, analytics, and orchestrated response between products"
      benefit2 = "Discover critical insights and findings you're missing now"
      benefit3 = "Avoid buying unnecessary tools"
      benefit4 = "Free yourself from vendor lock-in"
      icon = "icon-info"

  # Projects section
  [params.projects]
    enable = true
    title = "Projects"
    description = "OCA advances a growing body of open source projects."
    footertext = ''

    [[params.projects.row]]
      img = "led-panel.jpg"
      alt = "Kestrel"
      title = "Kestrel"
      subtitle = "Threat Hunting Language"
      description = "Provides an abstraction for threat hunters to focus on what to hunt instead of how to hunt."
      url = "https://github.com/opencybersecurityalliance/kestrel-lang"

    [[params.projects.row]]
      img = "stix-shifter-lib2-img.jpg"
      alt = "STIX Shifter"
      title = "STIX Shifter"
      subtitle = "Patterning Library"
      description = "Allows data to be normalized across domains for comprehensive security analysis"
      url = "https://github.com/opencybersecurityalliance/stix-shifter"

    [[params.projects.row]]
      img = "opendxl-message-img.jpg"
      alt = "OpenDXL Ontology"
      title = "OpenDXL Ontology"
      subtitle = "Messaging Format"
      description = "Enables real-time data exchange and cross-vendor orchestration"
      url = "https://github.com/opencybersecurityalliance/opendxl-ontology"

    [[params.projects.row]]
      img = "scap-data-img.jpg"
      alt = "NIST SCAP v2"
      title = "NIST SCAP v2"
      subtitle = "Data Collection Architecture"
      description = "Supports continuous monitoring for tracking assets' policy compliance"
      url = "https://csrc.nist.gov/projects/security-content-automation-protocol-v2/scapv2-community"

    [[params.projects.row]]
      img = "pace.jpg"
      alt = "PACE"
      title = "PACE"
      subtitle = "Posture Attribute Collection and Evaluation"
      description = "Helps to evaluate the posture assessment of computing resources."
      url = "https://github.com/opencybersecurityalliance/PACE"






  # About section
  [params.about]
    enable = true
    title = "About"
    description = 'An [OASIS Open Project](https://oasis-open-projects.org/), OCA operates under an inclusive, fair process that assures secure licensing and a path for recognition in international policy and procurement.'

    [[params.about.item]]
      name = "Mission"
      position = ""
      description = "Our goal is interoperability across cybersecurity products. We’re not another data sharing platform."
      button = "Read More"
      url = "/mission"
      img = "mission.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

    [[params.about.item]]
      name = "Governance"
      position = ""
      description = "Developers, corporate supporters, and technology consumers all have a voice in decision-making."
      button = "Meet our Leadership"
      url = "/governance"
      img = "governance.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Sponsors"
      position = ""
      description = "Leading cybersecurity vendors, enterprises, and nonprofits from around the world back the OCA."
      button = "Join Us"
      url = "/sponsors"
      img = "support.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]


  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Contact us for more details about sponsorship, or to learn more about the Alliance."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; OASIS Open. All Rights Reserved.'
    links = [
        ["icon-twitter", "https://twitter.com/OpenCyberAllnc"],
        ["icon-github", "https://github.com/opencybersecurityalliance"],
        ["icon-linkedin", "https://www.linkedin.com/company/open-cybersecurity-alliance/"],
        ["icon-youtube", "https://www.youtube.com/channel/UCjTpPl2oEGH_Ws251m827Cg"]
      ]
